apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-monitoring
spec:
  version: 8.4.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /login
            port: 5601
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /login
            port: 5601
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            memory: 2Gi
            cpu: 2
